### ISSUE TITLE
Syntax error in the fpm.toml of the FACE library

### ISSUE THREAD

**Issue by igirault** [szaghi/VTKFortran#40]
when trying to use VTKFortran with fpm, the build stage fails due to an old syntax error in toml file of the FACE library. The error seem to have been corrected in FACE, but the toml file of VTKFortran keeps pointing on an uncorrected version of FACE.

**Comment by szaghi** [comment]
@igirault thank you for reporting the bug, I am going to update the FACE submodule now.

**Comment by szaghi** [comment]
@igirault I have pushed a new commit with updated submodules, let me know if the fix works.

Kind regards,
Stefano

**Comment by igirault** [comment]
@szaghi thank you but it does not solve the problem : you need to modify the fpm.toml of FoXy and VTKFortran to point on the last version of StringiFor, whose fpm.toml file has already been corrected in https://github.com/szaghi/StringiFor/commit/5288871cc942aa2203e987af9d98d74ad7205d2c to point on the corrected version of Face.

**Comment by szaghi** [comment]
@igirault I do not use fpm, thus I am not sure how to correct its config. Anyway, I will try to fix it.
